name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 8.0
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        env:
          XDEBUG_MODE: coverage
        with:
          php_extensions: swoole xdebug
          php_version: 8.0
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text --whitelist ./src/
