name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: docker.io/crowphp/phpunit:1.1
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer install --dev
      - name: Run PHPUnit
        run: php -dxdebug.mode=coverage vendor/bin/phpunit --coverage-text --whitelist ./Crow
